### ISSUE TITLE
Streamline naming conventions

### ISSUE THREAD

**Issue by mansenfranzen** [mansenfranzen/pywrangler#24]
Collection of naming improvements:

- [x] streamline abstract and concrete variable names in [concretize_abstract_wrangler](https://github.com/mansenfranzen/pywrangler/blob/e34578ed496e0b86d2e38948b30e28b8c0aa4241/src/pywrangler/util/testing.py#L8)
- [x] make tuple instantiation more [readable](https://github.com/mansenfranzen/pywrangler/blob/e34578ed496e0b86d2e38948b30e28b8c0aa4241/src/pywrangler/wranglers.py#L101)
- [x] use fixture for concrete interval identifier in [testing wrangler](https://github.com/mansenfranzen/pywrangler/blob/e34578ed496e0b86d2e38948b30e28b8c0aa4241/tests/test_interfaces.py#L25)

**Comment by TobiasRasbold** [comment]
scheduled with branch #23

**Comment by mansenfranzen** [comment]
Fixed by #23
